Homework3/Models/City.cs
using System;
using System.Collections.Generic;

namespace Homework3.Models
{
    public class City
    {
        public int Id { get; set; }
        public string CityName { get; set; }
        public List<Data> Datas { get; set; } = new List<Data>();

        public override string ToString() { return CityName; }
    }
}

Homework3/Models/Data.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Homework3.Models
{
    public class Data
    {
        public int Id { get; set; }
        public DateTime Date { get; set; } = DateTime.Now;
        public int Cases { get; set; }
        public int Deaths { get; set; }
        public int Tested { get; set; }
        public int Population { get; set; }
        public int CityId2 { get; set; }
        [ForeignKey("CityId2")]
        public City City { get; set; }

        public override string ToString()
        {
            return $"{Date.ToShortDateString()}\t{Cases}\t{Deaths}\t{Tested}";
        }
    }
}

Homework3/Models/ErrorViewModel.cs
using System;

namespace Homework3.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Homework3/Controllers/CitiesController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using Homework3.Models;
using Homework3.Services;
using Microsoft.AspNetCore.Mvc;

namespace Homework3.Controllers
{
    public class CitiesController : Controller
    {
        private readonly ICityService _cityService;
        public CitiesController(ICityService cityService)
        {
            _cityService = cityService;
        }

        public IActionResult List()
        {
            return View(_cityService.GetCities());
        }

        public IActionResult View(int id)
        {
            City c = _cityService.GetCity(id);
            List<string> dates = new List<string>();
            List<int> cases = new List<int>();
            List<int> tested = new List<int>();
            List<int> deaths = new List<int>();
            int population = c.Datas[c.Datas.Count-1].Population;
            foreach (var data in c.Datas)
            {
                dates.Add(data.Date.ToString("d"));
                cases.Add(data.Cases);
                tested.Add(data.Tested);
                deaths.Add(data.Deaths);

            }
            //dates.Sort();
            ViewBag.Dates = dates;
            ViewBag.Tested = tested;
            ViewBag.Deaths = deaths;
            ViewBag.Cases = cases;
            ViewBag.Population = population;
            return View(c);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(string CityName, int Population)
        {
            _cityService.AddCity(CityName, Population);
            return RedirectToAction(nameof(List));
            //return Content($"{CityName} + {Population}");
        }
    }

}

Homework3/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using Homework3.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Homework3.Controllers
{

    public class FilesController : Controller
    {
        private readonly IFileService _fileService;

        public FilesController(IFileService fileService)
        {
            _fileService = fileService;
        }
        [HttpGet]
        public IActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Upload(IFormFile file, DateTime date)
        {
            using var reader = new StreamReader(file.OpenReadStream());
            var lines = new List<string>();
            string line;
            while ((line = reader.ReadLine()) != null)
                lines.Add(line);
            _fileService.Import(lines, date);
            return RedirectToAction("List", "Cities");
            //_cityService.List();
            //return View("~/Views/Cities/List.cshtml");
            //return View(_cityService.GetCities());
            //return Content($"{date}");
            //_fileService.upload();
            //return View("Display", lines);
        }
    }
}

Homework3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Homework3.Models;
using Homework3.Services;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Homework3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IHomeService _homeService;
        private readonly ICityService _cityService;

        public HomeController(ILogger<HomeController> logger, IHomeService homeService, ICityService cityService)
        {
            _logger = logger;
            _homeService = homeService;
            _cityService = cityService;
        }

        public IActionResult Index()
        {
            //Console.WriteLine($"{_homeService.List()}");
            ViewBag.CityName = _homeService.List().Select(e => new SelectListItem
            {
                Text = e.CityName,
                Value = e.Id.ToString()
            });
            return View(_homeService.List());
        }

        [HttpPost]
        public IActionResult Index(string id)
        {
            return Content($"{id}");
            //return View(_cityService.GetCity(id));
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Homework3/Views/Cities/Add.cshtml
@{
    ViewData["Title"] = "Add City";
}

<form method="post">
    <div class="form-group">
        <label for="CityName">Name</label>
        <input type="text" class="form-control" id="CityName" name="CityName">
    </div>
    <div class="form-group">
        <label for="Population">Population</label>
        <input type="number" class="form-control" id="Population" name="Population">
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
</form>

Homework3/Views/Cities/List.cshtml
@model List<City>
@{
    ViewData["Title"] = "Cities List";
}
<h4>Citites</h4>
<br />
<a asp-controller="Cities" asp-action="Add"><button>Add City</button></a>
<br />
<br />
<ul>
    @foreach (var city in Model)
    {
        <li>
            <a asp-controller="Cities" asp-action="View" asp-route-id="@city.Id">@city.CityName</a>
        </li>
    }
</ul>

Homework3/Views/Cities/View.cshtml
@model City
@{
    ViewData["Title"] = Model.CityName;
}

@section StyleSheets{
    <link rel="stylesheet" href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
}

<h1>@Model.CityName </h1>
<h3>Population - @ViewBag.Population</h3><hr>
<br />

<div class="cases"><h4>Cases</h4></div><hr>
<div class="deaths"><h4>Deaths</h4></div><hr>
<div class="tested"><h4>Tested</h4></div><hr>


@section Scripts{
    <script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
    <script>
        var data = {

            labels: @Json.Serialize(ViewBag.Dates),

            series: [
                @Json.Serialize(ViewBag.Cases)
            ]
        };
        new Chartist.Line('.cases', data);
    </script>
    <script>
        var data = {

            labels: @Json.Serialize(ViewBag.Dates),

            series: [
                @Json.Serialize(ViewBag.Deaths)
            ]
        };
        new Chartist.Line('.deaths', data);
    </script>
    <script>
        var data = {

            labels: @Json.Serialize(ViewBag.Dates),

            series: [
                @Json.Serialize(ViewBag.Tested)
            ]
        };
        new Chartist.Line('.tested', data);
    </script>

}

<div>
    <h4>Available data</h4>
    <table class="table">
        <tr>
            <th role="columnheader">Date</th>
            <th role="columnheader">Cases</th>
            <th role="columnheader">Deaths</th>
            <th role="columnheader">Tested</th>
        </tr>
        @foreach (var data in Model.Datas)
        {
            <tr>
                <td>@data.Date.ToString("d")</td>
                <td>@data.Cases</td>
                <td>@data.Deaths</td>
                <td>@data.Tested</td>
            </tr>
        }
    </table>
</div>

Homework3/Views/Files/Display.cshtml
@model List<string>

@foreach (var line in Model)
{
    <div>@line</div>
}

Homework3/Views/Files/Upload.cshtml
@{
    ViewData["Title"] = "Import Data";
}

<form method="post" enctype="multipart/form-data">
    CSV File: <input name="file" type="file">
    <br />
    <br />
    <div class="form-group">
        <label for="date">Date</label>
        <input type="date" class="form-control" id="date" name="date">
    </div>
    <button>Upload</button>
</form>

Homework3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<City>

<div class="text-center">
    <h1 class="display-4">Welcome To LocalCovid</h1>
</div>
<hr>
<hr>
<div>
    <h4>Import Data From CSV File </h4><button type="button" onclick="location.href='@Url.Action("Upload", "Files")'">Import Data </button>
</div>
<hr>
<br/>
<h4>Select a city to view its Available data</h4>
<div>
    <form method="post">
        <label for="Cities"><h5>Cities:</h5></label><br />
        <select name="City" id="Id" class="city">
            @foreach (var city in Model)
            {
                <option value=@city.Id>
                    @city.CityName
                </option>
            }

        </select>
    </form>
</div>

<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script>
    var id;
    $(document).ready(function () {
        $("select.city").change(function () {
            var selectedCity = $(this).children("option:selected").val();
            var url = "Cities/View/".concat(selectedCity);
            window.location.href = url;
        });
    });
</script>

Homework3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LocalCovid</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("StyleSheets", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LocalCovid</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="List">List Cities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="Add">Add City</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Files" asp-action="Upload">Import Data</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - LocalCovid By Jay Tandel
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>